name: 'Client pipeline coverage report'

defaults:
  run:
    working-directory: client

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'client/*'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # run tests + output coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2