name: 'Client pipeline coverage report'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'client/*'
jobs:
  coverage:

    defaults:
      run:
        working-directory: client
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # run tests + output coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: client
