name: 'Client pipeline'

defaults:
  run:
    working-directory: client
    
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'client/*'
jobs:

  lint:
        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Specify Node Version
        uses: actions/setup-node@v1
        with:
          node-version: "16.14"

      # cache BEFORE npm i to leverage cache
      # DOCS: 
      #   https://github.com/actions/cache
      # TODO: update to v2 
      - name: cache node-mods
        uses: actions/cache@v1
        with:
          # OS-dependent + package-manager dependent path val
          # NPM Cache docs: https://docs.npmjs.com/cli/v7/configuring-npm/folders
          path: ~/.npm
          # key docs: https://github.com/actions/cache#creating-a-cache-key
          #   os type
          #   hashing package-lock file for changes
          key: ${{runner.os}}-node-mods-${{ hashFiles('**/package-lock.json') }}
          # restore-keys docs: https://github.com/actions/cache#inputs
          # same value as previous key
          # first time it runs the cache, github wont find anything for the cache
          # prefix-only - the hash will be different each cache
          # must be regex matching or something
          restore-keys:  | 
            ${{runner.os}}-node-mods-
          # once workflow is done, github caches the hashed package-lock with the key :) 
          #   a post cache step gets added to the workflow by this action lib
      
          # install mods 
          - run: npm i

          # run linter
          - run npm run lint