name: 'pipeline coverage report'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.2'
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
